platform :ios, '9.2'
pod 'Toast-Swift', '~> 1.3.0'
pod 'KDEAudioPlayer'
xcodeproj 'VIBE_Client.xcodeproj'
use_frameworks!

target 'VIBE_Client' do
    pod 'Alamofire', '~> 3.0'
    pod 'SwiftyJSON'
end
